# Only used for CLion intellisense for now
cmake_minimum_required(VERSION 4.0)
project(PPlus)

add_subdirectory(AsyncRSP)
add_subdirectory(CodeMenu)
add_subdirectory(ftp)
add_subdirectory(MenuTest)
add_subdirectory(NetLog)
add_subdirectory(Physics)
add_subdirectory(pplusRecords)
add_subdirectory(Sandbox)